name: Deploying React + Python Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Installing Dependencies
        run: |
          npm cache clean --force && \
          npm install
        working-directory: ./Frontend
      - name: Building the Frontend Artifact
        run: npm run build
        working-directory: ./FrontEnd
      - name: Uploading the Frontend Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-output
          path: ./Frontend/dist
#   deploy:
#     runs-on: self-hosted
#     needs: build
#     steps:
#       - name: Downloading Frontend Build Artifact
#         uses: actions/download-artifact@v4
#         with:
#           name: frontend-output

#       - name: Removing old Files
#         run: sudo rm -rf /var/www/xai.harkirat.site/*
